### ISSUE TITLE
Cannot get simple example to work.

### ISSUE THREAD

**Issue by eventualbuddha** [asterjs/aster#4]
It seems something is wrong with aster.watch. With this [sample project](https://github.com/eventualbuddha/aster-test) I created, I get the error below when running `node build.js`. I tried going into the dependencies and fixing things a bit, but gave up after three changes. One change was to change part of `aster-watch/index.js` to bind to the gaze instance:

``` js
var _getWatched = Rx.Observable.fromNodeCallback(gaze.relative.bind(gaze), undefined, gaze);
```

Any ideas? Can you reproduce this?

```
/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1128
          throw e;
                ^
TypeError: Cannot read property 'options' of undefined
    at Gaze.relative (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/gaze/lib/gaze.js:350:53)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:5164:14
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at ConnectableObservable.connect (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:6093:67)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:6108:62
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:3824:27
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2817:31
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2118:19
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:3824:27
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2817:31
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at AnonymousObserver.m.setDisposable.sources.subscribe.isStopped [as _onNext] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2824:53)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1819:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at AutoDetachObserverPrototype.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8983:31)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at AnonymousObserver._onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:3832:26)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1819:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at AutoDetachObserverPrototype.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8983:31)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at AnonymousObserver._onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:3832:26)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1819:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at AutoDetachObserverPrototype.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8983:31)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1819:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at AutoDetachObserverPrototype.next (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8983:31)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1748:22)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2431:18
    at invokeAction (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:794:7)
    at Scheduler.scheduleNow [as _schedule] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1078:50)
    at Scheduler.Rx.Scheduler.schedulerProto.schedule (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:806:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2430:24
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1552:38
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:939:9
    at recursiveAction (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:883:9)
    at invokeRecImmediate (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:900:7)
    at Scheduler.scheduleNow [as _schedule] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1078:50)
    at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:816:19)
    at Scheduler.schedulerProto.scheduleRecursiveWithState (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:949:19)
    at Scheduler.schedulerProto.scheduleRecursive (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:938:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1530:43
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:3824:27
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:3824:27
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2817:31
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:7675:33
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8955:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at /Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:3824:27
    at setDisposable (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8943:60)
    at invokeAction [as action] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:794:7)
    at ScheduledItem.invokeCore (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:732:21)
    at ScheduledItem.invoke (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:720:44)
    at runTrampoline (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1108:18)
    at Scheduler.scheduleRelative [as _scheduleRelative] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1126:11)
    at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithRelativeAndState (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:837:19)
    at Scheduler.scheduleNow [as _schedule] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:1115:19)
    at Scheduler.Rx.Scheduler.schedulerProto.schedule (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:806:19)
    at AnonymousObservable.s [as _subscribe] (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:8953:34)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/donovan/Desktop/aster-test/node_modules/aster/node_modules/aster-watch/node_modules/rx/dist/rx.all.js:2019:19)
    at Object.<anonymous> (/Users/donovan/Desktop/aster-test/build.js:13:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by RReverser** [comment]
Thanks, it was already fixed in `aster-watch` but most of repos used `0.0.x` version which caused `^0.0.x` pattern not to check for newer versions (since, according to semver rules, any `0.0.x` and `0.0.y` are considered incompatible). I've runned script against all the repos to have at least `0.1.0` version and updated cross-dependencies manually so this and any consequent updates will be correctly retrieved by npm.

Thanks for reporting and sorry for inconveniences. Being one of first users can be always a bit problematic :)

**Comment by RReverser** [comment]
Here are PRs that fix the issue:
1. eventualbuddha/aster-test#1 - just dependency pattern update.
2. esnext/es6-class#10 - fix for generating transpiled code from ES6 class.

**Comment by RReverser** [comment]
@eventualbuddha Since esnext/es6-class#10 is merged, please let me know if example now works for you.

**Comment by eventualbuddha** [comment]
Works now. Thanks, @RReverser!
